=begin
#Chat API SDK

#The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.

The version of the OpenAPI document: 1.0.0
Contact: sale@chat-api.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::Class5QueuesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'Class5QueuesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::Class5QueuesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Class5QueuesApi' do
    it 'should create an instance of Class5QueuesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::Class5QueuesApi)
    end
  end

  # unit tests for clear_actions_queue
  # Clear outbound actions queue.
  # This method is needed when you accidentally sent thousands of actions in a row.
  # @param [Hash] opts the optional parameters
  # @return [ClearActionsQueueStatus]
  describe 'clear_actions_queue test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for clear_messages_queue
  # Clear outbound messages queue.
  # This method is needed when you accidentally sent thousands of messages in a row.
  # @param [Hash] opts the optional parameters
  # @return [ClearMessagesQueueStatus]
  describe 'clear_messages_queue test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_actions_queue
  # Get outbound messages queue.
  # When you create an action, all actions are queued up. If an action is not executed, it remains in the queue and will be sent for execution in time. again. The action cannot be executed due to the status of the device connected to the account.  This method give the last 100 actions in the queue.
  # @param [Hash] opts the optional parameters
  # @return [OutboundActions]
  describe 'show_actions_queue test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_messages_queue
  # Get outbound messages queue.
  # When sending messages, all messages are in the queue. If the message is not sent, then it remains in the queue and in time it will be sent again. The message may not be sent due to the status of the device connected to the account.   This method give the last 100 messages in the queue.
  # @param [Hash] opts the optional parameters
  # @return [OutboundMessages]
  describe 'show_messages_queue test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
