=begin
#Chat API SDK

#The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.

The version of the OpenAPI document: 1.0.0
Contact: sale@chat-api.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::Class4WebhooksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'Class4WebhooksApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::Class4WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Class4WebhooksApi' do
    it 'should create an instance of Class4WebhooksApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::Class4WebhooksApi)
    end
  end

  # unit tests for set_webhook
  # Sets the URL for receiving webhook
  # Sets the URL for receiving webhook notifications of new messages and message delivery events (ack).  **API responses in \&quot;Callbacks\&quot; tab**
  # @param webhook_url 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhookStatus]
  describe 'set_webhook test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
